# Generated by Django 3.2.19 on 2023-11-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre', max_length=100)),
                ('imagen', models.FileField(default='', upload_to='imagenes/portada', verbose_name='Imagen Portada')),
            ],
            options={
                'verbose_name_plural': 'Portada',
                'unique_together': {('nombre',)},
            },
        ),
    ]
