# Generated by Django 3.2.19 on 2023-11-15 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0002_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portada',
            name='imagen',
            field=models.FileField(default='', upload_to='imagenes/portada', verbose_name='Imagen Portada (1920 x 947 px)'),
        ),
        migrations.CreateModel(
            name='Reflexiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre', max_length=100)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha')),
                ('url_video', models.FileField(default='', upload_to='video/reflexiones', verbose_name='Video')),
            ],
            options={
                'verbose_name_plural': 'Portada',
                'unique_together': {('nombre',)},
            },
        ),
    ]
