# Generated by Django 3.2.19 on 2023-11-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0003_auto_20231115_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reflexiones',
            options={'verbose_name_plural': 'Reflexiones'},
        ),
        migrations.AlterField(
            model_name='reflexiones',
            name='url_video',
            field=models.CharField(default='', max_length=1000, verbose_name='Video'),
        ),
    ]
