# Generated by Django 3.2.19 on 2023-11-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0004_auto_20231115_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reflexiones',
            unique_together={('nombre', 'url_video')},
        ),
    ]
