# Generated by Django 3.2.19 on 2023-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0006_auto_20231115_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen_destacado',
            field=models.FileField(upload_to='imagenes/', verbose_name='Imagen Destacado (915 x 770 px)'),
        ),
    ]
